export const LINE_WORKSPACE_PAGE_TEMPLATE = `
<app-line-workspace
  [title]="lineDataConfig.title || 'Lines'"
  [lineDataConfig]="lineDataConfig"
  [lineFormGroup]="lineFormGroup"
  [lineReady]="lineReady"
  [selectedLines]="selectedLines"
  [viewMode]="viewMode"
  [saving]="saving"
  [loading]="loading"
  [showMoreButton]="showMoreButton"
  [showBackButton]="false"
  [deleteDisabled]="selectedLines.length === 0"
  [columnFilters]="columnFilters"
  [activeFilterCount]="activeFilterCount"
  [focusRowIndex]="focusRowIndex"
  [focusRequestId]="focusRequestId"
  [appendLoading]="appendLoading"
  [checkLineAll]="checkLineAll"
  [rowErrors]="rowErrors"
  [sortColumn]="sortColumn"
  [sortDirection]="sortDirection"
  [(showSearchBox)]="showSearchBox"
  [(searchText)]="searchText"
  (searchSubmit)="searchItem()"
  (columnFilterChange)="updateColumnFilter($event)"
  (sortChange)="updateSorting($event)"
  (clearFilters)="clearColumnFilters()"
  (add)="insertLineAt($event)"
  (copyLine)="copyLineAt($event)"
  (revertLine)="revertLine($event)"
  (editToggle)="changeViewMode()"
  (deleteSelected)="deleteLines()"
  (loadMore)="getLineData()"
  (lineSelect)="selectLineItem($event)"
  (selectAll)="selectAll()"
  (lineChange)="changeLineControl($event.event, $event.rowIndex)"
  (lineLeave)="leaveLineControl($event.event, $event.rowIndex)"
  (dropdownItemsLoaded)="dropdownItemsLoadedEvent($event.items, $event.control)"
  (blankRowDiscarded)="onBlankRowDiscarded()"
  (advancedFilterChange)="onAdvancedFilterChange($event)">
</app-line-workspace>
`;