import {
  DataSourceConfig,
  DataSurfaceConfig,
  EntryHeaderConfig,
  ListPageConfig,
} from '../../shared/erp-core/public-api';

const dataSurface: DataSurfaceConfig = {
  id: 'customer-master-grid',
  idField: 'systemId',
  columns: [
    {
      id: 'no',
      label: 'No.',
      field: 'no',
      isPrimary: true,
    },
    {
      id: 'name',
      label: 'Name',
      field: 'name',
      subtitleField: 'customerAccountGroup',
    },
    {
      id: 'city',
      label: 'City',
      field: 'city',
    },
    {
      id: 'countryCode',
      label: 'Country',
      field: 'countryCode',
    },
    {
      id: 'phoneNo',
      label: 'Phone',
      field: 'phoneNo',
    },
    {
      id: 'email',
      label: 'Email',
      field: 'email',
    },
    {
      id: 'currencyCode',
      label: 'Currency',
      field: 'currencyCode',
    },
    {
      id: 'paymentTermsCode',
      label: 'Payment Terms',
      field: 'paymentTermsCode',
    },
    {
      id: 'salespersonPurchaser',
      label: 'Salesperson',
      field: 'salespersonPurchaser',
    },
    {
      id: 'blocked',
      label: 'Blocked',
      field: 'blocked',
      type: 'badge',
      align: 'center',
    },
  ],
};

export const customerMasterListConfig: ListPageConfig & { dataSource: DataSourceConfig } = {
  id: 'customer-master',
  pageCode: 'CUSTOMER_MASTER',
  pageType: 'card',
  defaultOpenTarget: 'list',
  title: 'Customers',
  subtitle: 'Customer master records',
  module: 'Sales',
  company: 'TECSA',
  viewSuffix: 'Customer List',
  views: [
    { id: 'all', label: 'All' },
    { id: 'open', label: 'Open', filter: "blocked eq ''" },
    { id: 'blocked', label: 'Blocked', filter: "blocked ne ''" },
  ],
  activeViewId: 'all',
  commandSelectionPolicy: {
    defaultMode: 'none',
    commands: {
      'customer:sync-sample': 'none',
    },
  },
  commands: [
    {
      id: 'customer-refresh',
      label: 'Refresh Data',
      actionKey: 'refresh',
      surface: 'list',
      icon: 'bi bi-arrow-clockwise',
      group: 'system',
      order: 10,
      tooltip: 'Reload customer list from server',
    },
    {
      id: 'customer-sync-sample',
      label: 'Sync Sample',
      actionKey: 'customer:sync-sample',
      surface: 'list',
      icon: 'bi bi-cloud-arrow-up',
      group: 'integration',
      order: 30,
      tooltip: 'Sample config-first command for future master pages',
    },
  ],
  tools: {
    refresh: true,
    filter: true,
    advancedFilter: true,
    export: false,
    columns: true,
  },
  filterConfig: {
    enabled: true,
    storageKey: 'master.customers.filters',
    fields: [
      {
        field: 'no',
        label: 'Customer No.',
        type: 'text',
      },
      {
        field: 'name',
        label: 'Name',
        type: 'text',
      },
      {
        field: 'customerAccountGroup',
        label: 'Customer Account Group',
        type: 'dropdown',
        apiUrl: '/customerAccountGroups',
        valueField: 'code',
        labelField: 'description',
      },
      {
        field: 'countryCode',
        label: 'Country',
        type: 'dropdown',
        apiUrl: '/countries',
        valueField: 'code',
        labelField: 'name',
      },
      {
        field: 'blocked',
        label: 'Blocked',
        type: 'select',
        options: [
          { value: '', label: 'Open' },
          { value: 'Ship', label: 'Ship' },
          { value: 'Invoice', label: 'Invoice' },
        ],
      },
    ],
  },
  searchFields: ['no', 'name', 'customerAccountGroup', 'city', 'phoneNo', 'email'],
  searchPlaceholder: 'Search customer no, name, group, city, phone or email',
  behavior: {
    keyFallbackFields: ['systemId', 'no'],
    statusField: 'blocked',
    statusDefault: 'Open',
  },
  dataSource: {
    endpoint: '/customers',
    keyField: 'systemId',
    documentNoField: 'no',
    createFields: [
      'no',
      'name',
      'name2',
      'searchName',
      'address',
      'address2',
      'city',
      'postCode',
      'countryCode',
      'county',
      'phoneNo',
      'mobilePhoneNo',
      'email',
      'homePage',
      'contactNo',
      'territoryCode',
      'dimension1',
      'dimension2',
      'currencyCode',
      'languageCode',
      'customerAccountGroup',
      'businessAccountGroup',
      'taxBusinessGroup',
      'customerPricingGroup',
      'customerDiscountGroup',
      'paymentTermsCode',
      'paymentMethodCode',
      'financeChargeTerms',
      'reminderTermsCode',
      'salespersonPurchaser',
      'shipmentMethodCode',
      'shippingAgentCode',
      'locationCode',
      'docSendingProfile',
      'taxAreaCode',
      'taxLiable',
      'creditLimitLCY',
      'billToCustomer',
      'blocked',
      'registrationNo',
      'taxRegistrationNo',
      'numberSeries',
      'createdDate',
      'modifiedDate',
    ],
    updateBlockedFields: ['systemId', 'companyId'],
    supportsCreate: true,
    supportsUpdate: true,
    supportsDelete: true,
    pageSize: 20,
  },
  factPanel: {
    id: 'customer-fact-panel',
    label: 'Customer',
    title: 'Customer Overview',
    subtitle: 'Selection insights',
    enabled: true,
    defaultSectionId: 'identity',
    binding: {
      titleField: 'name',
      subtitleField: 'customerAccountGroup',
      summaryField: 'creditLimitLCY',
      summaryType: 'currency',
      labelField: 'no',
    },
    sections: [
      {
        id: 'identity',
        title: 'Identity',
        fields: [
          { id: 'no', label: 'No.', field: 'no' },
          { id: 'name', label: 'Name', field: 'name' },
          { id: 'group', label: 'Account Group', field: 'customerAccountGroup' },
          { id: 'billToCustomer', label: 'Bill-to Customer', field: 'billToCustomer' },
        ],
      },
      {
        id: 'contact',
        title: 'Contact',
        fields: [
          { id: 'city', label: 'City', field: 'city' },
          { id: 'country', label: 'Country', field: 'countryCode' },
          { id: 'phone', label: 'Phone', field: 'phoneNo' },
          { id: 'email', label: 'Email', field: 'email' },
        ],
      },
      {
        id: 'posting',
        title: 'Posting',
        fields: [
          { id: 'currency', label: 'Currency', field: 'currencyCode' },
          { id: 'paymentTerms', label: 'Payment Terms', field: 'paymentTermsCode' },
          { id: 'salesperson', label: 'Salesperson', field: 'salespersonPurchaser' },
        ],
        badges: [
          { id: 'blocked', label: 'Blocked', field: 'blocked' },
        ],
      },
    ],
  },
  dataSurface,
};

export const customerMasterHeaderConfig: EntryHeaderConfig = {
  dialogTitle: 'Customer',
  commandBar: {
    maxPrimaryActions: 4,
    maxVisibleGroups: 3,
  },
  attachmentsDefault: {
    headerFilesCount: 0,
    lineFilesCount: 0,
    canUpload: true,
    primaryActionLabel: 'Add attachment',
    primaryActionKey: 'dialog:attachments',
    context: {
      documentNoField: 'no',
      documentType: 'customer',
      documentStatusField: 'blocked',
    },
  },
  toolbarButtons: [
    {
      id: 'header-refresh-sample',
      label: 'Refresh Header',
      actionKey: 'refresh',
      surface: 'header',
      icon: 'bi bi-arrow-clockwise',
      group: 'system',
      order: 10,
      tooltip: 'Sample header command defined from config',
    },
    {
      id: 'header-customer-ledger-entries',
      label: 'Ledger Entries',
      actionKey: 'cmd:customer-ledger-entries',
      surface: 'header',
      icon: 'bi bi-journal-text',
      group: 'Navigate',
      order: 20,
      runModalPageId: 'customer-ledger-entry',
      runModalTarget: 'list',
      tooltip: 'Open customer ledger entries in run modal',
    },
  ],
  detailToolbarButtons: [
    {
      id: 'detail-close',
      label: 'Close',
      actionKey: 'cmd:close',
      surface: 'detail',
      order: 10,
    },
  ],
  sections: [
    {
      id: 'general',
      title: 'General',
      fields: [
        {
          key: 'no',
          label: 'Customer No.',
          type: 'text',
          required: true,
          placeholder: 'CUST-0001',
        },
        {
          key: 'name',
          label: 'Name',
          type: 'text',
          required: true,
          placeholder: 'Customer name',
        },
        {
          key: 'name2',
          label: 'Name 2',
          type: 'text',
          placeholder: 'Secondary name',
        },
        {
          key: 'customerAccountGroup',
          label: 'Customer Account Group',
          type: 'dropdown',
          required: true,
          api: '/customerAccountGroups',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'searchName',
          label: 'Search Name',
          type: 'text',
          placeholder: 'Search alias',
        },
        {
          key: 'billToCustomer',
          label: 'Bill-to Customer',
          type: 'dropdown',
          api: '/customers',
          valueField: 'no',
          labelField: ['name', 'no'],
        },
        {
          key: 'numberSeries',
          label: 'No. Series',
          type: 'dropdown',
          api: '/numberSeries',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'blocked',
          label: 'Blocked',
          type: 'select',
          options: [
            { label: 'Open', value: '' },
            { label: 'All', value: 'All' },
            { label: 'Ship', value: 'Ship' },
            { label: 'Invoice', value: 'Invoice' },
          ],
        },
      ],
    },
    {
      id: 'contact',
      title: 'Contact & Address',
      fields: [
        {
          key: 'address',
          label: 'Address',
          type: 'text',
          placeholder: 'Street address',
        },
        {
          key: 'address2',
          label: 'Address 2',
          type: 'text',
          placeholder: 'Additional address line',
        },
        {
          key: 'city',
          label: 'City',
          type: 'text',
          placeholder: 'City',
        },
        {
          key: 'postCode',
          label: 'Post Code',
          type: 'dropdown',
          api: '/postCodes',
          valueField: 'code',
          labelField: ['city', 'code'],
        },
        {
          key: 'countryCode',
          label: 'Country Code',
          type: 'dropdown',
          api: '/countries',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'county',
          label: 'County',
          type: 'text',
          placeholder: 'County or state',
        },
        {
          key: 'contactNo',
          label: 'Contact No.',
          type: 'dropdown',
          api: '/contacts',
          valueField: 'no',
          labelField: ['name', 'no'],
        },
        {
          key: 'phoneNo',
          label: 'Phone No.',
          type: 'text',
          placeholder: '+60...',
        },
        {
          key: 'mobilePhoneNo',
          label: 'Mobile Phone No.',
          type: 'text',
          placeholder: '+60...',
        },
        {
          key: 'email',
          label: 'Email',
          type: 'text',
          placeholder: 'name@example.com',
        },
        {
          key: 'homePage',
          label: 'Home Page',
          type: 'text',
          placeholder: 'https://example.com',
        },
      ],
    },
    {
      id: 'posting-groups',
      title: 'Posting & Pricing',
      fields: [
        {
          key: 'businessAccountGroup',
          label: 'Business Account Group',
          type: 'dropdown',
          api: '/businessAccountGroups',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'taxBusinessGroup',
          label: 'Tax Business Group',
          type: 'dropdown',
          api: '/taxBusinessGroups',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'customerPricingGroup',
          label: 'Customer Pricing Group',
          type: 'dropdown',
          api: '/customerPricingGroups',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'customerDiscountGroup',
          label: 'Customer Discount Group',
          type: 'dropdown',
          api: '/customerDiscountGroups',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'paymentTermsCode',
          label: 'Payment Terms Code',
          type: 'dropdown',
          api: '/paymentTerms',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'paymentMethodCode',
          label: 'Payment Method Code',
          type: 'dropdown',
          api: '/paymentMethods',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'financeChargeTerms',
          label: 'Finance Charge Terms',
          type: 'dropdown',
          api: '/financeChargeTerms',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'reminderTermsCode',
          label: 'Reminder Terms Code',
          type: 'dropdown',
          api: '/reminderTerms',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'currencyCode',
          label: 'Currency Code',
          type: 'dropdown',
          api: '/currencies',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'languageCode',
          label: 'Language Code',
          type: 'dropdown',
          api: '/languages',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'creditLimitLCY',
          label: 'Credit Limit (LCY)',
          type: 'number',
          placeholder: '0.00',
        },
      ],
    },
    {
      id: 'dimensions-logistics',
      title: 'Dimensions & Logistics',
      fields: [
        {
          key: 'dimension1',
          label: 'Dimension 1',
          type: 'dropdown',
          api: '/dimensions',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'dimension2',
          label: 'Dimension 2',
          type: 'dropdown',
          api: '/dimensions',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'salespersonPurchaser',
          label: 'Salesperson/Purchaser',
          type: 'dropdown',
          api: '/salespersonPurchasers',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'shipmentMethodCode',
          label: 'Shipment Method Code',
          type: 'dropdown',
          api: '/shipmentMethods',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'shippingAgentCode',
          label: 'Shipping Agent Code',
          type: 'dropdown',
          api: '/shippingAgents',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'locationCode',
          label: 'Location Code',
          type: 'dropdown',
          api: '/locations',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'territoryCode',
          label: 'Territory Code',
          type: 'dropdown',
          api: '/territories',
          valueField: 'code',
          labelField: ['name', 'code'],
        },
        {
          key: 'docSendingProfile',
          label: 'Doc Sending Profile',
          type: 'dropdown',
          api: '/docSendingProfiles',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
      ],
    },
    {
      id: 'tax-compliance',
      title: 'Tax & Compliance',
      fields: [
        {
          key: 'taxAreaCode',
          label: 'Tax Area Code',
          type: 'dropdown',
          api: '/taxAreas',
          valueField: 'code',
          labelField: ['description', 'code'],
        },
        {
          key: 'taxLiable',
          label: 'Tax Liable',
          type: 'boolean',
        },
        {
          key: 'registrationNo',
          label: 'Registration No.',
          type: 'text',
          placeholder: 'Registration number',
        },
        {
          key: 'taxRegistrationNo',
          label: 'Tax Registration No.',
          type: 'text',
          placeholder: 'Tax registration number',
        },
        {
          key: 'createdDate',
          label: 'Created Date',
          type: 'date',
        },
        {
          key: 'modifiedDate',
          label: 'Modified Date',
          type: 'date',
        },
      ],
    },
  ],
};
