export const environment = {
  // New ERP stack: local API only.
  authorizationType: 'Bearer',
  tenantId: '',
  clientId: '',
  clientSecret: '',
  username: '',
  password: '',
  secret: '',
  scope: '',
  tokenUrl: '',
  api: '/local-api/tecsa/procure/v1.0',
  apiBaseUrl: '/local-api/tecsa/procure/v1.0',
  authApiBaseUrl: '/local-api',
  externalApi: '',
  externalApiKey: '',
  bcCompany: '',
  bcTenant: '',
  bcEnvironment: '',
  production: false,
  isLive: false,
  sessionTimeout: 30,
  textLimitMax: 100,
  DocNoLimit: 20,
  lisenceApiCore: '',
  licenseCheckToken: '',
  licenseApi: '',
  oauthTokenApi: ''
};
