export const environment = {
  // TODO(security): Production secrets must not remain in the frontend. Use backend/proxy token exchange.
  authorizationType: 'Bearer',
  tenantId: 'bde30a6a-c467-4a6d-942a-d9dfb6b3eebf',
  clientId: '482021aa-36db-426d-9cf0-48f03d533958',
  clientSecret: 'nxv8Q~rFnNiimf-TX8T21eiUl5uNgqZLj7Xrvdmq.',
  username: '',
  password: '',
  secret: 'TECSA-Cenergi@2021',
  scope: 'https://api.businesscentral.dynamics.com/.default',
  tokenUrl: 'https://login.microsoftonline.com/bde30a6a-c467-4a6d-942a-d9dfb6b3eebf/oauth2/v2.0/token',
  api: 'https://api.businesscentral.dynamics.com/v2.0/tecsa.com.my/procure360/api/tecsa/procure/v1.0',
  apiBaseUrl: 'https://api.businesscentral.dynamics.com/v2.0/tecsa.com.my/Procure360/api/tecsa/procure/v1.0',
  externalApi: 'https://cenergi-portal.com/CenergiApi/api/',
  externalApiKey: 'Zq3t6w9z$C&F)J@NcRfUjXn2r5u7x!A%D*G-KaPdSgVkYp3s6v',
  bcCompany: '',
  bcTenant: 'tecsa.com.my',
  bcEnvironment: 'Procure360',
  production: true,
  isLive: false,
  sessionTimeout: 30,
  textLimitMax: 100,
  DocNoLimit: 20,
  lisenceApiCore: 'https://licensesandbox.tecsatech.com/api/V1/',
  licenseCheckToken: '$2a$08$3hgtwuKN2zMXeJORvon.pOldOi5eqNkF3i3KLxLXdukDDigtN92By',
  licenseApi: 'https://licensesandbox.tecsatech.com/api/V1/CheckLoginPermission',
  oauthTokenApi: 'https://azuretoken.tecsasoft.com/api/'
};
