export const environment = {
  // Fresh local development configuration.
  authorizationType: 'Bearer',
  tenantId: '',
  clientId: '',
  clientSecret: '',
  username: '',
  password: '',
  secret: '',
  scope: '',
  tokenUrl: '',
   api: 'https://filazerpbackend.tecsasoft.com/public/api/tecsa/procure/v1.0',
  apiBaseUrl: 'https://filazerpbackend.tecsasoft.com/public/api/tecsa/procure/v1.0',
  authApiBaseUrl: 'https://filazerpbackend.tecsasoft.com/public/api/tecsa/procure/v1.0',
  // api: '/local-api/tecsa/procure/v1.0',
  // apiBaseUrl: '/local-api/tecsa/procure/v1.0',
  // authApiBaseUrl: '/local-api/tecsa/procure/v1.0',
  externalApi: '',
  externalApiKey: '',
  bcCompany: '',
  bcTenant: '',
  bcEnvironment: '',
  production: false,
  isLive: false,
  sessionTimeout: 30,
  textLimitMax: 100,
  DocNoLimit: 20,
  lisenceApiCore: '',
  licenseCheckToken: '',
  licenseApi: '',
  oauthTokenApi: ''
};
