import { PurchaseTableProfile } from './purchase-table-profile.models';

const commonStopPatterns = [
  /\bsub\s*total\b/i,
  /\bsubtotal\b/i,
  /\bgrand\s+total\b/i,
  /\btotal\s+(?:amount|rm|myr|usd|gbp|incl\.?\s*vat|excluding|excluding\s+vat)\b/i,
  /\bvat\s+amount\s+specification\b/i,
  /\bship-?to\s+address\b/i,
  /\bbank\b/i,
  /\baccount\s+no\.?\b/i,
  /\bauthorized\s+signature\b/i,
  /\bremarks?\b/i,
  /\bfooter\b/i,
  /\bpage\s+\d+\b/i,
  /\bbranches\b/i,
];

export const PURCHASE_TABLE_PROFILES: PurchaseTableProfile[] = [
  {
    code: 'ITEM_CODE_DESCRIPTION_QTY_UOM_COST_AMOUNT',
    name: 'Item Code / Description / Quantity / UOM / Cost / Amount',
    requiredHeaderAliases: [
      ['item code', 'item no', 'product code', 'code'],
      ['description', 'details', 'particulars'],
      ['quantity', 'qty'],
      ['amount', 'line amount'],
    ],
    optionalHeaderAliases: [['s/no', 'sno', 'no.'], ['uom', 'unit'], ['unit cost', 'unit price', 'rate']],
    columnAliases: {
      externalItemCode: ['item code', 'item no', 'product code', 'code'],
      description: ['description', 'details', 'particulars'],
      quantity: ['quantity', 'qty'],
      uom: ['uom', 'unit', 'unit of measure'],
      unitPrice: ['unit cost', 'unit price', 'rate', 'cost'],
      lineAmount: ['amount', 'line amount', 'total'],
      vatPercent: ['vat %', 'tax %', 'gst %'],
      discountPercent: ['discount %', 'disc %'],
    },
    stopPatterns: commonStopPatterns,
    confidenceWeight: 1,
  },
  {
    code: 'NO_DESCRIPTION_QTY_UNIT_COST_VAT_AMOUNT',
    name: 'No / Description / Quantity / Unit Cost / VAT / Amount',
    requiredHeaderAliases: [
      ['no.', 'no', 'item no', 'code'],
      ['description', 'details', 'particulars'],
      ['quantity', 'qty'],
      ['line amount', 'amount'],
    ],
    optionalHeaderAliases: [['unit', 'uom'], ['direct unit cost', 'unit cost', 'unit price'], ['vat %']],
    columnAliases: {
      externalItemCode: ['no.', 'no', 'item no', 'product code', 'code'],
      description: ['description', 'details', 'particulars'],
      quantity: ['quantity', 'qty'],
      uom: ['unit', 'uom', 'unit of measure'],
      unitPrice: ['direct unit cost', 'unit cost', 'unit price', 'rate'],
      vatPercent: ['vat %', 'tax %', 'gst %'],
      lineAmount: ['line amount', 'amount', 'total'],
    },
    stopPatterns: commonStopPatterns,
    confidenceWeight: 0.98,
  },
  {
    code: 'NO_DESCRIPTION_QTY_UNIT_OF_MEASURE_DIRECT_COST_AMOUNT',
    name: 'No / Description / Quantity / Unit of Measure / Direct Cost / Amount',
    requiredHeaderAliases: [
      ['no.', 'no', 'item no', 'code'],
      ['description', 'details', 'particulars'],
      ['quantity', 'qty'],
      ['line amount', 'amount'],
    ],
    optionalHeaderAliases: [['unit of measure', 'unit', 'uom'], ['direct unit cost', 'unit cost', 'unit price', 'rate'], ['vat %']],
    columnAliases: {
      externalItemCode: ['no.', 'no', 'item no', 'product code', 'code'],
      description: ['description', 'details', 'particulars'],
      quantity: ['quantity', 'qty'],
      uom: ['unit of measure', 'uom', 'unit'],
      unitPrice: ['direct unit cost', 'unit cost', 'unit price', 'rate'],
      vatPercent: ['vat %', 'tax %', 'gst %'],
      lineAmount: ['line amount', 'amount', 'total'],
    },
    stopPatterns: commonStopPatterns,
    confidenceWeight: 1,
  },
  {
    code: 'GENERIC_DESCRIPTION_QTY_RATE_AMOUNT',
    name: 'Generic Description / Quantity / Rate / Amount',
    requiredHeaderAliases: [
      ['description', 'details', 'particulars'],
      ['quantity', 'qty'],
      ['amount', 'line amount', 'total'],
    ],
    optionalHeaderAliases: [['no.', 'no', 'item code', 'product code'], ['unit', 'uom'], ['unit price', 'unit cost', 'rate']],
    columnAliases: {
      externalItemCode: ['no.', 'no', 'item code', 'item no', 'product code', 'code'],
      description: ['description', 'details', 'particulars'],
      quantity: ['quantity', 'qty'],
      uom: ['unit', 'uom', 'unit of measure'],
      unitPrice: ['unit price', 'unit cost', 'direct unit cost', 'rate', 'cost'],
      lineAmount: ['amount', 'line amount', 'total'],
      vatPercent: ['vat %', 'tax %', 'gst %'],
      discountPercent: ['discount %', 'disc %'],
    },
    stopPatterns: commonStopPatterns,
    confidenceWeight: 0.86,
  },
];
