import {
  DataSourceConfig,
  EntryHeaderConfig,
  LineConfig,
  ListPageConfig,
} from '../../shared/erp-core/public-api';

type PermissionSetListConfig = ListPageConfig & { dataSource: DataSourceConfig };

const yesNoOptions = [
  { label: 'No', value: false },
  { label: 'Yes', value: true },
];

const lineToolbarButtons = [
  {
    id: 'line-new',
    label: 'Line',
    actionKey: 'cmd:line-new',
    group: 'Process',
    isPrimary: true,
    order: 10,
    icon: 'bi bi-plus-lg',
  },
  {
    id: 'line-delete',
    label: 'Delete',
    actionKey: 'cmd:line-delete',
    group: 'Process',
    order: 20,
    icon: 'bi bi-trash',
  },
];

export const permissionSetSetupListConfig: PermissionSetListConfig = {
  pageType: 'setup',
  pageId: 'permission-set-setup',
  title: 'Permission Set Setup',
  subtitle: 'Page and action permission rules',
  module: 'Admin',
  viewSuffix: 'permission sets',
  views: [{ id: 'all', label: 'All' }],
  activeViewId: 'all',
  tools: {
    refresh: true,
    filter: true,
    advancedFilter: true,
    export: false,
    columns: true,
  },
  searchFields: ['permissionSetId', 'permissionSetCode', 'permissionSetName', 'description'],
  searchPlaceholder: 'Search permission set id, code or name',
  dataSource: {
    endpoint: '/permission-sets',
    keyField: 'systemId',
    documentNoField: 'permissionSetId',
    defaultSort: 'permissionSetCode asc',
    supportsCreate: true,
    supportsUpdate: true,
    supportsDelete: true,
    pageSize: 25,
  },
  dataSurface: {
    id: 'permission-set-setup-grid',
    idField: 'systemId',
    columns: [
      {
        id: 'permissionSetId',
        field: 'permissionSetId',
        label: 'Permission Set ID',
        isPrimary: true,
        factPanel: { sectionId: 'identity', sectionTitle: 'Identity', order: 10, fallback: '-' },
      },
      {
        id: 'permissionSetCode',
        field: 'permissionSetCode',
        label: 'Code',
        factPanel: { sectionId: 'identity', sectionTitle: 'Identity', order: 20, fallback: '-' },
      },
      {
        id: 'permissionSetName',
        field: 'permissionSetName',
        label: 'Name',
        factPanel: { sectionId: 'identity', sectionTitle: 'Identity', order: 30, fallback: '-' },
      },
      {
        id: 'description',
        field: 'description',
        label: 'Description',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 10, fallback: '-' },
      },
    ],
  },
  factPanel: {
    enabled: true,
    title: 'Permission Set',
    binding: {
      titleField: 'permissionSetName',
      titleFallbackFields: ['permissionSetId'],
      subtitleField: 'permissionSetCode',
      summaryField: 'description',
    },
  },
};

export const permissionSetSetupHeaderConfig: EntryHeaderConfig = {
  dialogTitle: 'Permission Set Setup',
  toolbarButtons: [],
  sections: [
    {
      id: 'general',
      title: 'General',
      fields: [
        {
          key: 'permissionSetId',
          label: 'Permission Set ID',
          type: 'text',
          valueType: 'text',
          required: true,
          factPanel: { sectionId: 'identity', sectionTitle: 'Identity', order: 10, fallback: '-' },
        },
        {
          key: 'permissionSetCode',
          label: 'Code',
          type: 'text',
          valueType: 'text',
          required: true,
          factPanel: { sectionId: 'identity', sectionTitle: 'Identity', order: 20, fallback: '-' },
        },
        {
          key: 'permissionSetName',
          label: 'Name',
          type: 'text',
          valueType: 'text',
          required: true,
          factPanel: { sectionId: 'identity', sectionTitle: 'Identity', order: 30, fallback: '-' },
        },
        {
          key: 'description',
          label: 'Description',
          type: 'textarea',
          valueType: 'text',
          factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 10, fallback: '-' },
        },
      ],
    },
    {
      id: 'audit',
      title: 'Audit',
      fields: [
        { key: 'systemId', label: 'System ID', type: 'text', valueType: 'text', readonly: true },
        { key: 'createdAt', label: 'Created At', type: 'date', valueType: 'date', readonly: true },
        { key: 'updatedAt', label: 'Updated At', type: 'date', valueType: 'date', readonly: true },
      ],
    },
  ],
};

export const permissionSetSetupLineConfig: LineConfig = {
  placement: { mode: 'after-section', afterSectionId: 'general' },
  selectable: true,
  editable: true,
  toolbarButtons: lineToolbarButtons,
  dataSource: {
    endpoint: '/permission-set-rules',
    keyField: 'systemId',
    parentKeyField: 'permissionSetId',
    documentNoField: 'permissionSetId',
    lineNo: true,
    defaultSort: 'lineNo asc',
    createFields: [
      'permissionSetId',
      'lineNo',
      'pageId',
      'actionId',
      'canRead',
      'canCreate',
      'canUpdate',
      'canDelete',
      'canExecute',
      'isIndirect',
    ],
    updateBlockedFields: ['systemId', 'permissionSetId'],
  },
  lineKeyField: 'lineNo',
  columns: [
    { id: 'lineNo', field: 'lineNo', label: 'Line No.', valueType: 'number', cellType: 'text', align: 'end' },
    {
      id: 'pageId',
      field: 'pageId',
      label: 'Page',
      valueType: 'text',
      cellType: 'dropdown',
      api: '/app-pages',
      valueField: 'pageId',
      labelField: ['pageName', 'pageCode', 'routePath'],
      factPanel: { sectionId: 'target', sectionTitle: 'Target', order: 10, fallback: '-' },
    },
    {
      id: 'actionId',
      field: 'actionId',
      label: 'Action',
      valueType: 'text',
      cellType: 'dropdown',
      api: '/page-actions',
      valueField: 'actionId',
      labelField: ['actionName', 'actionCode'],
      factPanel: { sectionId: 'target', sectionTitle: 'Target', order: 20, fallback: 'All actions' },
    },
    {
      id: 'canRead',
      field: 'canRead',
      label: 'Read',
      valueType: 'boolean',
      cellType: 'select',
      options: yesNoOptions,
      factPanel: { sectionId: 'access', sectionTitle: 'Access', order: 10, fallback: 'false' },
    },
    {
      id: 'canCreate',
      field: 'canCreate',
      label: 'Create',
      valueType: 'boolean',
      cellType: 'select',
      options: yesNoOptions,
      factPanel: { sectionId: 'access', sectionTitle: 'Access', order: 20, fallback: 'false' },
    },
    {
      id: 'canUpdate',
      field: 'canUpdate',
      label: 'Update',
      valueType: 'boolean',
      cellType: 'select',
      options: yesNoOptions,
      factPanel: { sectionId: 'access', sectionTitle: 'Access', order: 30, fallback: 'false' },
    },
    {
      id: 'canDelete',
      field: 'canDelete',
      label: 'Delete',
      valueType: 'boolean',
      cellType: 'select',
      options: yesNoOptions,
      factPanel: { sectionId: 'access', sectionTitle: 'Access', order: 40, fallback: 'false' },
    },
    {
      id: 'canExecute',
      field: 'canExecute',
      label: 'Execute',
      valueType: 'boolean',
      cellType: 'select',
      options: yesNoOptions,
      factPanel: { sectionId: 'access', sectionTitle: 'Access', order: 50, fallback: 'false' },
    },
    {
      id: 'isIndirect',
      field: 'isIndirect',
      label: 'Indirect',
      valueType: 'boolean',
      cellType: 'select',
      options: yesNoOptions,
      factPanel: { sectionId: 'access', sectionTitle: 'Access', order: 60, fallback: 'false' },
    },
  ],
};
