import {
  CommandConfig,
  DataSourceConfig,
  EntryHeaderConfig,
  EntryFooterSectionConfig,
  LineConfig,
  ListPageConfig,
} from '../../shared/erp-core/public-api';

export const purchaseOrderHeaderConfig: EntryHeaderConfig = {
  dialogTitle: 'Purchase Order',
  toolbarButtons: [
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Release',
      actionKey: 'cmd:release',
      group: 'Process',
      isPrimary: true,
      order: 10,
      icon: 'bi bi-arrow-repeat',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Re-Open',
      actionKey: 'cmd:reopen',
      group: 'Process',
      order: 20,
      icon: 'bi bi-box-arrow-in-right',
    },
    {
      label: 'Pre payment',
      actionKey: 'cmd:prepayment',
      group: 'Process',
      isPrimary: true,
      order: 30,
      icon: 'bi bi-credit-card',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Send Approval Request',
      actionKey: 'cmd:SendApprovalRequest',
      group: 'Approval',
      isPrimary: true,
      order: 40,
      icon: 'bi bi-send',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Cancel Approval Request',
      actionKey: 'cmd:CancelApprovalRequest',
      group: 'Approval',
      order: 50,
      icon: 'bi bi-x-circle',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'GRN Review',
      actionKey: 'cmd:GRNReview',
      group: 'Review',
      order: 60,
      icon: 'bi bi-file-earmark-check',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Cancel GRN Review',
      actionKey: 'cmd:CancelGRNReview',
      group: 'Review',
      order: 70,
      icon: 'bi bi-file-earmark-x',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Invoice Review',
      actionKey: 'cmd:InvoiceReview',
      group: 'Review',
      order: 80,
      icon: 'bi bi-receipt',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Cancel Invoice Review',
      actionKey: 'cmd:CancelInvoiceReview',
      group: 'Review',
      order: 90,
      icon: 'bi bi-x-square',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Post',
      actionKey: 'cmd:Post',
      group: 'Process',
      isPrimary: true,
      order: 100,
      icon: 'bi bi-cloud-upload',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Convert to Variation Order',
      actionKey: 'cmd:ConverttoVariationOrder',
      group: 'Process',
      order: 110,
      icon: 'bi bi-arrow-left-right',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Manual PO Cancel',
      actionKey: 'cmd:manualPOCancel',
      group: 'More',
      order: 120,
      icon: 'bi bi-ban',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Submit Workflow',
      actionKey: 'cmd:SubmitWorkflow',
      group: 'Approval',
      order: 130,
      icon: 'bi bi-send',
    },
    // Real PO command from old app. UI/config reference only; business logic is not implemented yet.
    {
      label: 'Cancel Workflow',
      actionKey: 'cmd:CancelWorkflow',
      group: 'Approval',
      order: 140,
      icon: 'bi bi-x-circle',
    },
  ],
  sections: [
    {
      id: 'header-main',
      title: 'Primary Details',
      fields: [
        {
          key: 'number',
          label: 'No',
          type: 'text',
          valueType: 'text',
          readonly: true,
          factPanel: { sectionId: 'document', sectionTitle: 'Document', order: 10, fallback: '-' },
        },
        { key: 'dueDate', label: 'Due Date', type: 'date', valueType: 'date', readonly: true },
        {
          key: 'buyFromVendorNumber',
          label: 'Vendor No',
          type: 'dropdown',
          valueType: 'text',
          api: ['/vendorsAPI', '/vendors'],
          valueField: 'number',
          labelField: 'name',
          fill: {
            buyFromVendorName: 'name',
          },
        },
        {
          key: 'orderDate',
          label: 'Order Date',
          type: 'date',
          valueType: 'date',
          readonly: true,
          factPanel: { sectionId: 'document', sectionTitle: 'Document', order: 30, fallback: '-' },
        },
        {
          key: 'buyFromVendorName',
          label: 'Vendor Name',
          type: 'text',
          valueType: 'text',
          width: 'wide',
          readonly: true,
          factPanel: {
            sectionId: 'document',
            sectionTitle: 'Document',
            label: 'Vendor',
            order: 20,
            fallback: '-',
          },
        },
        {
          key: 'requestedReceiptDate',
          label: 'Requested Receipt Date',
          type: 'date',
          valueType: 'date',
          readonly: true,
        },
        {
          key: 'buyFromAddress',
          label: 'Address',
          type: 'text',
          valueType: 'text',
          width: 'wide',
          readonly: true,
        },
        {
          key: 'purchaserCode',
          label: 'Purchaser Code',
          type: 'dropdown',
          valueType: 'text',
          api: '/salespersonPurchasers',
          valueField: 'code',
          labelField: 'name',
        },
        {
          key: 'buyFromCountryOrRegionCode',
          label: 'Country',
          type: 'text',
          valueType: 'text',
          readonly: true,
        },
        {
          key: 'status',
          label: 'Status',
          type: 'text',
          valueType: 'text',
          readonly: true,
          defaultValue: 'Open',
          factPanel: { sectionId: 'review', sectionTitle: 'Review', order: 10, fallback: 'Open' },
        },
        {
          key: 'buyFromPostCode',
          label: 'Post Code',
          type: 'text',
          valueType: 'text',
          readonly: true,
        },
        { key: 'documentDate', label: 'Document Date', type: 'date', valueType: 'date' },
        { key: 'buyFromCity', label: 'City', type: 'text', valueType: 'text', readonly: true },
        { key: 'orderNumber', label: 'Order No', type: 'text', valueType: 'text', readonly: true },
        {
          key: 'buyFromContactNo',
          label: 'Contact No',
          type: 'text',
          valueType: 'text',
          readonly: true,
        },
        { key: 'vendorOrderNumber', label: 'Vendor Order No', type: 'text', valueType: 'text' },
        { key: 'vendorInvoiceNumber', label: 'Vendor Invoice No', type: 'text', valueType: 'text' },
        {
          key: 'vendorShipmentNumber',
          label: 'Vendor Shipment No',
          type: 'text',
          valueType: 'text',
        },
        { key: 'quoteNumber', label: 'Quote No', type: 'text', valueType: 'text', readonly: true },
      ],
    },
    {
      id: 'financial',
      title: 'Financial & Delivery Info',
      fields: [
        {
          key: 'shortcutDimension1Code',
          label: 'PROJECT',
          type: 'dropdown',
          valueType: 'text',
          api: [
            "/dimensionsValues?$filter=DimensionCode eq 'PROJECT'",
            '/shortcutDimension1Values',
            "/dimensionValues?$filter=DimensionCode eq 'PROJECT'",
          ],
          optionsSkipWhenSuperAdmin: true,
          valueField: 'code',
          labelField: 'name',
        },
        {
          key: 'shortcutDimension2Code',
          label: 'DEPARTMENT/COST CNTR',
          type: 'dropdown',
          valueType: 'text',
          api: [
            "/dimensionsValues?$filter=DimensionCode eq 'DEPARTMENT/COST CNTR'",
            '/shortcutDimension2Values',
            "/dimensionValues?$filter=DimensionCode eq 'DEPARTMENT'",
          ],
          optionsSkipWhenSuperAdmin: true,
          valueField: 'code',
          labelField: 'name',
        },
        {
          key: 'paymentTermsCode',
          label: 'Payment Terms Code',
          type: 'dropdown',
          valueType: 'text',
          api: '/paymentTerms',
          valueField: 'code',
          labelField: 'description',
        },
        { key: 'validityDate', label: 'Validity Date', type: 'date', valueType: 'date' },
        { key: 'deliveryDate', label: 'Delivery Date', type: 'date', valueType: 'date' },
        { key: 'yourReference', label: 'Your Reference', type: 'text', valueType: 'text' },
        { key: 'paymentReference', label: 'Payment Reference', type: 'text', valueType: 'text' },
        {
          key: 'currencyCode',
          label: 'Currency',
          type: 'dropdown',
          valueType: 'text',
          readonly: true,
          api: ['/currencyCodes', '/currencies'],
          valueField: 'code',
          labelField: 'description',
        },
        {
          key: 'accessCenter',
          label: 'Access center',
          type: 'dropdown',
          valueType: 'text',
          api: ['/accessCenters', '/AccessCenters'],
          optionsSkipWhenSuperAdmin: true,
          valueField: 'code',
          labelField: 'name',
        },
        { key: 'prepayment', label: 'Pre payment %', type: 'number', valueType: 'number' },
      ],
    },
    {
      id: 'remarks',
      title: 'Remarks',
      fields: [
        { key: 'remark', label: 'Remark', type: 'textarea', valueType: 'text', width: 'wide' },
        {
          key: 'postingDate',
          label: 'Posting Date',
          type: 'date',
          valueType: 'date',
          factPanel: { sectionId: 'document', sectionTitle: 'Document', order: 40, fallback: '-' },
        },
      ],
    },
  ],
};

export const purchaseOrderLineConfig: LineConfig = {
  placement: {
    mode: 'after-section',
    afterSectionId: 'header-main',
  },
  dataSource: {
    endpoint: '/purchaseOrderLines',
    keyField: 'systemId',
    parentKeyField: 'documentNo',
    documentNoField: 'number',
    parentFixedFields: { documentType: 'Order' },
    createFields: ['documentType', 'documentNo', 'lineNo', 'type', 'no', 'quantity'],
    updateBlockedFields: ['systemId', 'id', 'documentNo', 'lineNo'],
    defaultSort: 'lineNo',
  },
  lineKeyField: 'lineNo',
  toolbarButtons: [
    {
      label: 'Line',
      actionKey: 'cmd:line-new',
      group: 'Process',
      isPrimary: true,
      order: 10,
      icon: 'bi bi-plus-lg',
    },
    { label: 'Insert', actionKey: 'cmd:line-insert', group: 'Process', order: 20 },
    {
      label: 'Delete',
      actionKey: 'cmd:line-delete',
      group: 'Process',
      order: 25,
      icon: 'bi bi-trash',
    },
    {
      label: 'Attachments',
      actionKey: 'dialog:attachments',
      group: 'More',
      order: 30,
      icon: 'bi bi-paperclip',
    },
  ],
  columns: [
    {
      id: 'type',
      label: 'Type',
      field: 'type',
      valueType: 'text',
      cellType: 'dropdown',
      options: [
        { label: 'G/L Account', value: 'G/L Account', api: '/glAccounts' },
        { label: 'Item', value: 'Item', api: '/Items' },
        { label: 'Fixed Asset', value: 'Fixed Asset', api: '/fixedAssets' },
        { label: 'Comment', value: ' ' },
      ],
    },
    {
      id: 'no',
      label: 'No',
      field: 'no',
      valueType: 'text',
      cellType: 'dropdown',
      valueField: ['no', 'number', 'code'],
      labelField: ['description', 'name'],
      fill: {
        description: 'description',
        unitOfMeasure: ['baseUnitOfMeasure', 'unitOfMeasureCode'],
        directUnitCost: ['directUnitCost', 'unitCost', 'unitPrice'],
      },
    },
    {
      id: 'description',
      label: 'Description',
      field: 'description',
      valueType: 'text',
      cellType: 'text',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 10, fallback: '-' },
    },
    {
      id: 'unitOfMeasure',
      label: 'Unit Of Measure',
      field: 'unitOfMeasure',
      valueType: 'text',
      cellType: 'dropdown',
      api: '/unitOfMeasures',
      valueField: 'code',
      labelField: 'description',
    },
    {
      id: 'locationCode',
      label: 'Location',
      field: 'locationCode',
      valueType: 'text',
      cellType: 'dropdown',
      api: '/locations',
      valueField: 'code',
      labelField: 'name',
    },
    {
      id: 'quantity',
      label: 'Quantity',
      field: 'quantity',
      valueType: 'number',
      cellType: 'text',
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 20, fallback: '0' },
    },
    {
      id: 'directUnitCost',
      label: 'Original Cost/Unit',
      field: 'directUnitCost',
      valueType: 'number',
      cellType: 'text',
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 30, fallback: '0' },
    },
    {
      id: 'lineAmount',
      label: 'PO Amount',
      field: 'lineAmount',
      valueType: 'number',
      cellType: 'text',
      readonly: true,
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 40, fallback: '0' },
    },
    {
      id: 'amountToInvoice',
      label: 'Amount To Invoice',
      field: 'amountToInvoice',
      valueType: 'number',
      cellType: 'text',
      readonly: true,
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 50, fallback: '0' },
    },
    {
      id: 'amountInvoiced',
      label: 'Amount Invoiced',
      field: 'amountInvoiced',
      valueType: 'number',
      cellType: 'text',
      readonly: true,
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 60, fallback: '0' },
    },
    {
      id: 'Attachment',
      label: '',
      cellType: 'icon',
      buttonIcon: 'bi bi-paperclip',
      buttonTitle: 'Line attachment',
      actionKey: 'dialog:attachments',
    },
  ],
  calculation: [
    {
      target: 'lineAmount',
      formula: 'quantity * directUnitCost',
    },
    {
      target: 'amountToInvoice',
      formula: 'lineAmount',
    },
  ],
  totalsCalculation: {
    defaults: {
      subtotal: '0.00',
      sst: '0.00',
      total: '0.00',
      difference: '0.00',
    },
    format: {
      type: 'currency',
      currencyCodeHeaderField: 'currencyCode',
    },
    totals: {
      subtotal: { formula: 'sum(lineAmount)' },
      sst: { kind: 'default' },
      total: { formula: 'sum(lineAmount)' },
      difference: { formula: 'sum(lineAmount) - sum(amountInvoiced)' },
    },
  },
  footerSections: [
    {
      id: 'document-totals',
      rows: [
        {
          id: 'amount-excl-sst',
          label: 'Amount Excl. SST',
          source: 'total',
          totalKey: 'subtotal',
          order: 10,
        },
        {
          id: 'sst',
          label: 'SST',
          source: 'total',
          totalKey: 'sst',
          order: 20,
        },
        {
          id: 'total-incl-sst',
          label: 'Total Incl. SST',
          source: 'total',
          totalKey: 'total',
          emphasis: true,
          order: 30,
        },
      ],
    },
  ] satisfies EntryFooterSectionConfig[],
};

export const purchaseOrderListCommandsConfig: CommandConfig[] = [
  // Demo list toolbar actions only. Business logic can be added by handling these action keys.
  {
    id: 'po-review',
    label: 'Review',
    actionKey: 'cmd:po-review',
    group: 'process',
    icon: 'bi bi-check2-square',
  },
  {
    id: 'po-send',
    label: 'Send',
    actionKey: 'cmd:po-send',
    group: 'process',
    icon: 'bi bi-send',
  },
  {
    id: 'po-print',
    label: 'Print',
    actionKey: 'cmd:po-print',
    group: 'documents',
    icon: 'bi bi-printer',
  },
  {
    id: 'po-export-file',
    label: 'Export File',
    actionKey: 'cmd:po-export-file',
    group: 'documents',
    icon: 'bi bi-file-earmark-arrow-down',
  },
  {
    id: 'po-more-action',
    label: 'More Action',
    actionKey: 'cmd:po-more-action',
    group: 'more',
    icon: 'bi bi-three-dots',
  },
];

export const purchaseOrderListConfig: ListPageConfig & { dataSource: DataSourceConfig } = {
  id: 'purchase-order',
  pageType: 'document',
  defaultOpenTarget: 'list',
  title: 'Purchase Order',
  module: 'Purchase',
  company: 'Cronus International Ltd.',
  viewSuffix: 'purchase orders',
  views: [
    { id: 'all', label: 'All' },
    { id: 'open', label: 'Open', filter: "status eq 'Open'" },
    { id: 'posted', label: 'Posted', filter: "status eq 'Posted'" },
    { id: 'exception', label: 'Exception', filter: "status eq 'Exception'" },
  ],
  activeViewId: 'all',
  filterConfig: {
    enabled: true,
    storageKey: 'purchase-order-list',
  },
  commandSelectionPolicy: {
    defaultMode: 'single',
  },
  commands: purchaseOrderListCommandsConfig,
  dataSource: {
    endpoint: '/purchaseOrderHeaders',
    contractProfileKey: 'purchaseOrderHeaders',
    keyField: 'systemId',
    documentNoField: 'number',
    autoGenerateNumber: true,
    lazyCreateOnFirstInput: true,
    defaultSort: 'number',
    pageSize: 20,
  },
  dataSurface: {
    columns: [
      {
        field: 'number',
        label: 'No',
        type: 'text',
        width: '84px',
        isPrimary: true,
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 10, fallback: '-' },
      },
      {
        field: 'buyFromVendorName',
        label: 'Buy-from Vendor Name',
        type: 'text',
        width: '268px',
        subtitleField: 'buyFromVendorNumber',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 20, fallback: '-' },
      },
      {
        field: 'vendorStatus',
        label: 'Vendor Status',
        type: 'text',
        width: '190px',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 25, fallback: '-' },
      },
      {
        field: 'orderDate',
        label: 'Order Date',
        type: 'date',
        width: '132px',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 30, fallback: '-' },
      },
      {
        field: 'postingDate',
        label: 'Posting Date',
        type: 'date',
        width: '132px',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 40, fallback: '-' },
      },
      {
        field: 'status',
        label: 'Status',
        type: 'badge',
        width: '132px',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 50, fallback: '-' },
      },
      {
        field: 'paymentTermsCode',
        label: 'Payment Terms',
        type: 'text',
        width: '118px',
        factPanel: { sectionId: 'details', sectionTitle: 'Details', order: 60, fallback: '-' },
      },
      {
        field: 'prepayment',
        label: 'Prepayment %',
        type: 'number',
        width: '126px',
        align: 'end',
        factPanel: { sectionId: 'amounts', sectionTitle: 'Amounts', order: 5, fallback: '0' },
      },
      {
        field: 'currencyCode',
        label: 'Currency',
        type: 'text',
        hidden: true,
      },
      {
        field: 'amount',
        label: 'Amount',
        type: 'currency',
        width: '146px',
        align: 'end',
        factPanel: { sectionId: 'amounts', sectionTitle: 'Amounts', order: 15, fallback: '0' },
      },
      {
        field: 'amountIncludingVAT',
        label: 'Amount Including VAT',
        type: 'currency',
        width: '164px',
        align: 'end',
        factPanel: { sectionId: 'amounts', sectionTitle: 'Amounts', order: 20, fallback: '0' },
      },
      {
        field: 'grnReviewStatus',
        label: 'GRN Review',
        type: 'text',
        width: '124px',
        factPanel: { sectionId: 'review', sectionTitle: 'Review', order: 10, fallback: '-' },
      },
      {
        field: 'invoiceReviewStatus',
        label: 'Invoice Review',
        type: 'text',
        width: '132px',
        factPanel: { sectionId: 'review', sectionTitle: 'Review', order: 20, fallback: '-' },
      },
      {
        field: 'manualPoCancel',
        label: 'Manual PO Cancel',
        type: 'boolean',
        hidden: true,
        factPanel: { sectionId: 'review', sectionTitle: 'Review', order: 30, fallback: 'false' },
      },
      {
        field: 'variationOrder',
        label: 'Variation Order',
        type: 'boolean',
        width: '132px',
        factPanel: { sectionId: 'review', sectionTitle: 'Review', order: 40, fallback: 'false' },
      },
      {
        field: 'systemModifiedAt',
        label: 'Modified',
        type: 'date',
        hidden: true,
      },
      {
        field: 'createdBy',
        label: 'Created By',
        type: 'text',
        hidden: true,
        factPanel: { sectionId: 'system', sectionTitle: 'System', order: 20 },
      },
    ],
  },
};
