import {
  DataSourceConfig,
  EntryHeaderConfig,
  LineConfig,
  ListPageConfig,
} from '../../shared/erp-core/public-api';

export const purchaseOrderHeaderConfig: EntryHeaderConfig = {
  dialogTitle: 'Purchase Order',
  toolbarButtons: [
    {
      label: 'Pre payment',
      actionKey: 'cmd:prepayment',
      group: 'Process',
      isPrimary: true,
      order: 10,
      icon: 'bi bi-credit-card',
      runModalTarget: 'list',
      runModalPageId: 'prepayment',
    },
  ],
  sections: [
    {
      id: 'header-main',
      title: 'Primary Details',
      fields: [
        {
          key: 'number',
          label: 'No',
          type: 'text',
          valueType: 'text',
          readonly: true,
          factPanel: { sectionId: 'document', sectionTitle: 'Document', order: 10, fallback: '-' },
        },
        { key: 'dueDate', label: 'Due Date', type: 'date', valueType: 'date', readonly: true },
        {
          key: 'buyFromVendorNumber',
          label: 'Vendor No',
          type: 'dropdown',
          valueType: 'text',
          api: ['/vendorsAPI', '/vendors'],
          valueField: 'number',
          labelField: 'name',
          fill: {
            buyFromVendorName: 'name',
          },
        },
        {
          key: 'orderDate',
          label: 'Order Date',
          type: 'date',
          valueType: 'date',
          readonly: true,
          factPanel: { sectionId: 'document', sectionTitle: 'Document', order: 30, fallback: '-' },
        },
        {
          key: 'buyFromVendorName',
          label: 'Vendor Name',
          type: 'text',
          valueType: 'text',
          width: 'wide',
          readonly: true,
          factPanel: {
            sectionId: 'document',
            sectionTitle: 'Document',
            label: 'Vendor',
            order: 20,
            fallback: '-',
          },
        },
        {
          key: 'requestedReceiptDate',
          label: 'Requested Receipt Date',
          type: 'date',
          valueType: 'date',
          readonly: true,
        },
        {
          key: 'buyFromAddress',
          label: 'Address',
          type: 'text',
          valueType: 'text',
          width: 'wide',
          readonly: true,
        },
        {
          key: 'purchaserCode',
          label: 'Purchaser Code',
          type: 'dropdown',
          valueType: 'text',
          api: '/salespersonPurchasers',
        },
        {
          key: 'buyFromCountryOrRegionCode',
          label: 'Country',
          type: 'text',
          valueType: 'text',
          readonly: true,
        },
        {
          key: 'status',
          label: 'Status',
          type: 'text',
          valueType: 'text',
          readonly: true,
          defaultValue: 'Open',
          factPanel: { sectionId: 'review', sectionTitle: 'Review', order: 10, fallback: 'Open' },
        },
        {
          key: 'buyFromPostCode',
          label: 'Post Code',
          type: 'text',
          valueType: 'text',
          readonly: true,
        },
        { key: 'documentDate', label: 'Document Date', type: 'date', valueType: 'date' },
        { key: 'buyFromCity', label: 'City', type: 'text', valueType: 'text', readonly: true },
        { key: 'orderNumber', label: 'Order No', type: 'text', valueType: 'text', readonly: true },
        {
          key: 'buyFromContactNo',
          label: 'Contact No',
          type: 'text',
          valueType: 'text',
          readonly: true,
        },
        { key: 'vendorOrderNumber', label: 'Vendor Order No', type: 'text', valueType: 'text' },
        { key: 'vendorInvoiceNumber', label: 'Vendor Invoice No', type: 'text', valueType: 'text' },
        {
          key: 'vendorShipmentNumber',
          label: 'Vendor Shipment No',
          type: 'text',
          valueType: 'text',
        },
        { key: 'quoteNumber', label: 'Quote No', type: 'text', valueType: 'text', readonly: true },
      ],
    },
    {
      id: 'financial',
      title: 'Financial & Delivery Info',
      fields: [
        {
          key: 'shortcutDimension1Code',
          label: 'PROJECT',
          type: 'dropdown',
          valueType: 'text',
          api: [
            "/dimensionsValues?$filter=DimensionCode eq 'PROJECT'",
            '/shortcutDimension1Values',
            "/dimensionValues?$filter=DimensionCode eq 'PROJECT'",
          ],
          optionsSkipWhenSuperAdmin: true,
        },
        {
          key: 'shortcutDimension2Code',
          label: 'DEPARTMENT/COST CNTR',
          type: 'dropdown',
          valueType: 'text',
          api: [
            "/dimensionsValues?$filter=DimensionCode eq 'DEPARTMENT/COST CNTR'",
            '/shortcutDimension2Values',
            "/dimensionValues?$filter=DimensionCode eq 'DEPARTMENT'",
          ],
          optionsSkipWhenSuperAdmin: true,
        },
        {
          key: 'paymentTermsCode',
          label: 'Payment Terms Code',
          type: 'dropdown',
          valueType: 'text',
          api: '/paymentTerms',
        },
        { key: 'validityDate', label: 'Validity Date', type: 'date', valueType: 'date' },
        { key: 'deliveryDate', label: 'Delivery Date', type: 'date', valueType: 'date' },
        { key: 'yourReference', label: 'Your Reference', type: 'text', valueType: 'text' },
        { key: 'paymentReference', label: 'Payment Reference', type: 'text', valueType: 'text' },
        {
          key: 'currencyCode',
          label: 'Currency',
          type: 'dropdown',
          valueType: 'text',
          readonly: true,
          api: ['/currencyCodes', '/currencies'],
        },
        {
          key: 'responsibilityCenter',
          label: 'Responsibility center',
          type: 'dropdown',
          valueType: 'text',
          api: ['/portalResponsibilityCentres', '/responsibilityCenters', '/ResponsibilityCenters'],
          optionsSkipWhenSuperAdmin: true,
        },
        { key: 'prepayment', label: 'Pre payment %', type: 'number', valueType: 'number' },
      ],
    },
    {
      id: 'remarks',
      title: 'Remarks',
      fields: [
        { key: 'remark', label: 'Remark', type: 'textarea', valueType: 'text', width: 'wide' },
        {
          key: 'postingDate',
          label: 'Posting Date',
          type: 'date',
          valueType: 'date',
          factPanel: { sectionId: 'document', sectionTitle: 'Document', order: 40, fallback: '-' },
        },
      ],
    },
  ],
};

export const purchaseOrderLineConfig: LineConfig = {
  placement: {
    mode: 'after-section',
    afterSectionId: 'header-main',
  },
  dataSource: {
    endpoint: '/purchaseOrderLines',
    keyField: 'systemId',
    parentKeyField: 'documentNo',
    parentFixedFields: { documentType: 'Order' },
    createFields: ['documentType', 'documentNo', 'lineNo', 'type', 'no', 'quantity'],
    updateBlockedFields: ['systemId', 'id', 'documentNo', 'lineNo'],
    defaultSort: 'lineNo',
  },
  toolbarButtons: [
    {
      label: 'Line',
      actionKey: 'cmd:line-new',
      group: 'Process',
      isPrimary: true,
      order: 10,
      icon: 'bi bi-plus-lg',
    },
    { label: 'Insert', actionKey: 'cmd:line-insert', group: 'Process', order: 20 },
    {
      label: 'Delete',
      actionKey: 'cmd:line-delete',
      group: 'Process',
      order: 25,
      icon: 'bi bi-trash',
    },
    {
      label: 'Attachments',
      actionKey: 'dialog:attachments',
      group: 'More',
      order: 30,
      icon: 'bi bi-paperclip',
    },
  ],
  columns: [
    {
      id: 'type',
      label: 'Type',
      field: 'type',
      valueType: 'text',
      cellType: 'dropdown',
      fill: {
        description: 'description',
      },
      options: [
        { label: 'G/L Account', value: 'G/L Account', api: '/glAccounts' },
        { label: 'Item', value: 'Item', api: '/Items' },
        { label: 'Fixed Asset', value: 'Fixed Asset', api: '/fixedAssets' },
        { label: 'Comment', value: ' ' },
      ],
    },
    {
      id: 'no',
      label: 'No',
      field: 'no',
      valueType: 'text',
      cellType: 'dropdown',
    },
    {
      id: 'description',
      label: 'Description',
      field: 'description',
      valueType: 'text',
      cellType: 'text',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 10, fallback: '-' },
    },
    {
      id: 'unitOfMeasure',
      label: 'Unit Of Measure',
      field: 'unitOfMeasure',
      valueType: 'text',
      cellType: 'dropdown',
      api: '/unitOfMeasures',
    },
    {
      id: 'locationCode',
      label: 'Location',
      field: 'locationCode',
      valueType: 'text',
      cellType: 'dropdown',
      api: '/locations',
    },
    {
      id: 'quantity',
      label: 'Quantity',
      field: 'quantity',
      valueType: 'number',
      cellType: 'text',
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 20, fallback: '0' },
    },
    {
      id: 'directUnitCost',
      label: 'Original Cost/Unit',
      field: 'directUnitCost',
      valueType: 'number',
      cellType: 'text',
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 30, fallback: '0' },
    },
    {
      id: 'lineAmount',
      label: 'PO Amount',
      field: 'lineAmount',
      valueType: 'number',
      cellType: 'text',
      readonly: true,
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 40, fallback: '0' },
    },
    {
      id: 'amountToInvoice',
      label: 'Amount To Invoice',
      field: 'amountToInvoice',
      valueType: 'number',
      cellType: 'text',
      readonly: true,
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 50, fallback: '0' },
    },
    {
      id: 'amountInvoiced',
      label: 'Amount Invoiced',
      field: 'amountInvoiced',
      valueType: 'number',
      cellType: 'text',
      readonly: true,
      align: 'end',
      factPanel: { sectionId: 'line', sectionTitle: 'Line', order: 60, fallback: '0' },
    },
    {
      id: 'Attachment',
      label: '',
      cellType: 'icon',
      buttonIcon: 'bi bi-paperclip',
      buttonTitle: 'Line attachment',
      actionKey: 'dialog:attachments',
    },
  ],
};

export const purchaseOrderListConfig: ListPageConfig & { dataSource: DataSourceConfig } = {
  title: 'Purchase Order',
  module: 'Purchase',
  company: 'Cronus International Ltd.',
  viewSuffix: 'purchase orders',
  views: [
    { id: 'all', label: 'All' },
    { id: 'open', label: 'Open', filter: "status eq 'Open'" },
    { id: 'posted', label: 'Posted', filter: "status eq 'Posted'" },
    { id: 'exception', label: 'Exception', filter: "status eq 'Exception'" },
  ],
  activeViewId: 'all',
  tools: {
    advancedFilter: true,
  },
  filterConfig: {
    enabled: true,
    storageKey: 'purchase-order-list',
  },
  standardActions: {
    new: true,
    delete: true,
    refresh: true,
  },
  dataSource: {
    endpoint: '/purchaseOrderHeaders',
    contractProfileKey: 'purchaseOrderHeaders',
    keyField: 'systemId',
    documentNoField: 'number',
    autoGenerateNumber: true,
    lazyCreateOnFirstInput: true,
    defaultSort: 'number',
    pageSize: 20,
    supportsCreate: true,
    supportsUpdate: true,
    supportsDelete: true,
  },
  dataSurface: {
    columns: [
      { field: 'number', label: 'No', type: 'text', isPrimary: true },
      {
        field: 'buyFromVendorName',
        label: 'Buy-from Vendor Name',
        type: 'text',
        subtitleField: 'buyFromVendorNumber',
      },
      { field: 'orderDate', label: 'Order Date', type: 'date' },
      { field: 'postingDate', label: 'Posting Date', type: 'date' },
      { field: 'status', label: 'Status', type: 'badge' },
      { field: 'currencyCode', label: 'Currency', type: 'text' },
      {
        field: 'amountIncludingVat',
        label: 'Amount Including VAT',
        type: 'currency',
        align: 'end',
      },
      { field: 'systemModifiedAt', label: 'Modified', type: 'date' },
    ],
  },
};
